# ww4.0, @2022
#

openapi: 3.0.0

# General Data Model Information
info:
  title: ww4zero Project
  description: Data model for the MOFREITA component developped under the ww4.0 project
  version: 0.0.1
  contact:
    name: Digitalization da Carpintaria Portuguesa Mofreita
    url: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/

components:
  schemas:
    #verified
    Organization:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/organization.yaml#/organization"

    #verified
    Project:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/project.yaml#/project"

    #verified
    Owner:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/owner.yaml#/owner"

    #verified
    Worker:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/worker.yaml#/worker"

    #verified
    Consumable:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/consumable.yaml#/consumable"

    #verified
    Part:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/part.yaml#/part"

    #verified
    Machine:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/machine.yaml#/machine"

    #verified
    Assembly:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/assembly.yaml#/assembly"

    #verified
    Budget:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/budget.yaml#/budget"

    #verified
    Expedition:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/expedition.yaml#/expedition"

    #verified
    Module:
      $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/module.yaml#/module

    #verified
    Furniture:
      $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/furniture.yaml#/furniture

    #verified
    Group:
      $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/group.yaml#/group

    MachineTask:
      $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/machineTask.yaml#/machineTask

    WorkerTask:
      $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/workerTask.yaml#/workerTask

    #verified
    LeftOver:
      $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/leftOver.yaml#/leftover

paths:
  /ngsi-ld/v1/entities:
    get:
      responses:
        "200":
          description: "OK"
          content:
            application/ld+json:
              schema:
                type: object
