# ww4.0, @2022
#

openapi: 3.0.0

# General Data Model Information
info:
  title: ww4zero Project
  description: Data model for the MOFREITA component developped under the ww4.0 project
  version: 0.0.1
  contact:
    name: Digitalization da Carpintaria Portuguesa Mofreita
    url: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/

servers:
  - url: http://woodwork4.ddns.net/ww4/api/v1
    description: Production environment

paths:
  /organization:
    $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/organization.yaml#/paths/~1organization
  /organization/{id}:
    $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/organization.yaml#/paths/~1organization~1{id}

  /project:
    $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/project.yaml#/paths/~1project
  /project/{id}:
    $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/project.yaml#/paths/~1project~1{id}
  /project/{id}/attrs:
    $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/project.yaml#/paths/~1project~1{id}~1attrs
  /project/{id}/attrs/{attr}:
    $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/project.yaml#/paths/~1project~1{id}~1attrs~1{attr}

  /owner:
    $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/owner.yaml#/paths/~1owner
  /owner/{id}:
    $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/owner.yaml#/paths/~1owner~1{id}

  /worker:
    $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/worker.yaml#/paths/~1worker
  /worker/{id}:
    $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/worker.yaml#/paths/~1worker~1{id}

  /consumable:
    $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/consumable.yaml#/paths/~1consumable
  /consumable/{id}:
    $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/consumable.yaml#/paths/~1consumable~1{id}
  /consumable/{id}/attrs:
    $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/consumable.yaml#/paths/~1consumable~1{id}~1attrs
  /consumable/{id}/attrs/{attr}:
    $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/consumable.yaml#/paths/~1consumable~1{id}~1attrs~1{attr}

  /part:
    $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/part.yaml#/paths/~1part
  /part/{id}:
    $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/part.yaml#/paths/~1part~1{id}
  /part/{id}/attrs:
    $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/part.yaml#/paths/~1part~1{id}~1attrs
  /part/{id}/attrs/{attr}:
    $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/part.yaml#/paths/~1part~1{id}~1attrs~1{attr}

  /module:
    $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/module.yaml#/paths/~1module
  /module/{id}:
    $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/module.yaml#/paths/~1module~1{id}
  /module/{id}/attrs:
    $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/module.yaml#/paths/~1module~1{id}~1attrs
  /module/{id}/attrs/{attr}:
    $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/module.yaml#/paths/~1module~1{id}~1attrs~1{attr}

  /leftover:
    $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/leftOver.yaml#/paths/~1leftover
  /leftover/{id}:
    $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/leftOver.yaml#/paths/~1leftover~1{id}
  /leftover/{id}/attrs:
    $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/leftOver.yaml#/paths/~1leftover~1{id}~1attrs
  /leftover/{id}/attrs/{attr}:
    $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/leftOver.yaml#/paths/~1leftover~1{id}~1attrs~1{attr}

components:
  schemas:
    Organization:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/organization.yaml#/schemas/organization"
    Project:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/project.yaml#/schemas/project"
    Owner:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/owner.yaml#/schemas/owner"
    Worker:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/worker.yaml#/schemas/worker"
    Consumable:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/consumable.yaml#/schemas/consumable"
    Part:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/part.yaml#/schemas/part"
    Machine:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/machine.yaml#/machine"
    Assembly:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/assembly.yaml#/assembly"
    Budget:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/budget.yaml#/budget"
    Expedition:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/expedition.yaml#/expedition"
    Module:
      $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/module.yaml#/schemas/module
    Furniture:
      $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/furniture.yaml#/furniture
    Group:
      $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/group.yaml#/group
    MachineTask:
      $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/machineTask.yaml#/machineTask
    WorkerTask:
      $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/workerTask.yaml#/workerTask
    LeftOver:
      $ref: https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/leftOver.yaml#/schemas/leftover
