# ww4.0, @2022
# 

openapi: 3.0.0

# General Data Model Information
info:
  title: ww4zero Project
  description: Data model for the MOFREITA component developped under the ww4.0 project
  version: 0.0.1
  contact:
    name: Digitalização da Carpintaria Portuguesa Mofreita
    url: https://projectww4zero.pt/
  
components:
  schemas: 
    Organization:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/organization.yaml#/organization"
    Project:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/project.yaml#/project"
    Owner:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/owner.yaml#/owner"
    Worker:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/worker.yaml#/worker"
    Consumable:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/consumable.yaml#/consumable"
    Part:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/part.yaml#/part"
    Action:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/action.yaml#/action"
    Assembly:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/assembly.yaml#/assembly"
    Budget:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/budget.yaml#/budget"
    expedition:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/expedition.yaml#/expeditionDate"


paths:
  /ngsi-ld/v1/entities:
    get:
      responses:
        '200':
          description: 'OK'
          content:
            application/ld+json:
              schema:
                type: object