# ww4.0, @2022
# 

openapi: 3.0.0

# General Data Model Information
info:
  title: ww4zero Project
  description: Data model for the MOFREITA component developped under the ww4.0 project
  version: 0.0.1
  contact:
    name: Digitalization da Carpintaria Portuguesa Mofreita
    url: https://projectww4zero.pt/
  
components:
  schemas: 
    Organization:
      $ref: "https://raw.githubusercontent.com/More-Collaborative-Laboratory/ww4zero/main/organization.yaml/#Organization" 



paths:
  /ngsi-ld/v1/entities:
    get:
      responses:
        '200':
          description: 'OK'
          content:
            application/ld+json:
              schema:
                type: object