project:
    title: Project
    type: object
    description: Contains the information of a project
    properties:
      id:
        description: Projects id Identifier
        type: string
        format: uri
        example: urn:ngsi-ld:Project:[uuid]
        x-ngsi:
          type: Property
          
      name: 
        description: Project name
        type: string
        example: MUEBLE-WC
        x-ngsi:
          uri: "https://schema.org/name"
          uri-prefix: "https://schema.org/"
          model: https://schema.org/name
          type: Property

      category: #movel wc, movel cozinha, movel 
        description: Movel type
        type: string
        example: Movel cozinha
        x-ngsi:
          uri: "https://projectww4zero.pt/dataModel/category"
          uri-prefix: "https://projectww4zero.pt/dataModel/"
          type: Property

      status:  #list ou enum 
        description: Indicates the actual workers station
          * `waiting` - Projects budget approved
          * `working` - Projects parts are already in the factorys floor
          * `finished` - Projects parts are all done
          * `assembly` - Projects parts are being assembled in the test zone 
          * `expedition` - The request from a client is already out from the factory
        type: string
        enum: 
          - Waiting
          - working
          - finished
          - assembly
          - expedition
        example: expedition
        x-ngsi:
          uri: "https://projectww4zero.pt/dataModel/status"
          uri-prefix: "https://projectww4zero.pt/dataModel/"
          type: Property

      nestingTag:
        anyOf:
          - description: 'Relationship property: Identifies the number to put on a wood coming from cut list'
            maxLength: 256
            minLength: 1
            pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
            type: string
          - description: 'Relationship property: number of tag comming from cut list'
            format: uri
            type: string
        description: 'Identification of the final tag to past in wood part originated on nesting station'
        x-ngsi:
          uri: "https://projectww4zero.pt/dataModel/nestingTag"
          uri-prefix: "https://projectww4zero.pt/dataModel/"
          type: Relationship

      producedBy:
        anyOf:
          - description: 'Relationship property: Identifies the operator envolved in the produced stations'
            maxLength: 256
            minLength: 1
            pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
            type: string
          - description: 'Relationship property: linking the workers and the project giveName'
            format: uri
            type: string
        description: 'Identification of the operators giveName that are working in specific project Name'
        x-ngsi:
          uri: "https://projectww4zero.pt/dataModel/producedBy"
          uri-prefix: "https://projectww4zero.pt/dataModel/"
          type: Relationship

      orderBy:
        anyOf:
          - description: 'Relationship property: Identifies the Owner giveName or familyName or taxID that the project belongs to'
            maxLength: 256
            minLength: 1
            pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
            type: string
          - description: 'Relationship property: Identifies a project by the associated giveName from the owner'
            format: uri
            type: string
        description: 'Identification of the owner name associated to the project with status in execution'
        x-ngsi:
          uri: "https://projectww4zero.pt/dataModel/orderBy"
          uri-prefix: "https://projectww4zero.pt/dataModel/"
          type: Relationship

      budget:
        anyOf:
          - description: 'Relationship property: Identifies the Budget related to the actual project'
            maxLength: 256
            minLength: 1
            pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
            type: string
          - description: 'Relationship property: Identifies a project by the associated giveName from the Budget'
            format: uri
            type: string
        description: 'Documentos'
        x-ngsi:
          uri: "https://projectww4zero.pt/dataModel/budget"
          uri-prefix: "https://projectww4zero.pt/dataModel/"
          type: Relationship

^
      acessories:
        anyOf:
          - description: 'Relationship property: Identifies list of consumables corresponding to a determinated project'
            maxLength: 256
            minLength: 1
            pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
            type: string
          - description: 'Relationship property: acessories list from cut list'
            format: uri
            type: string
        description: 'Identification of all nedded acessories for specific project'
        x-ngsi:
          uri: "https://projectww4zero.pt/dataModel/acessories"
          uri-prefix: "https://projectww4zero.pt/dataModel/"
          type: Relationship

      part:
        anyOf:
          - description: 'Relationship property: Indicates the name of all parts corresponding to a specific project'
            maxLength: 256
            minLength: 1
            pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
            type: string
          - description: 'Relationship property: number and names for the parts comming from cut list for specific project'
            format: uri
            type: string
        description: 'Identification of the parts for a specific project comming from cut list'
        x-ngsi:
          uri: "https://projectww4zero.pt/dataModel/part"
          uri-prefix: "https://projectww4zero.pt/dataModel/"
          type: Relationship

      assemblyBy:
        anyOf:
          - description: 'Relationship property: Identifies wich parts were assembled by a specific worker'
            maxLength: 256
            minLength: 1
            pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
            type: string
          - description: 'Relationship property: parts of a project assembled by work giveName or familyName'
            format: uri
            type: string
        description: 'Identification assembled parts belong to some project made for some worker'
        x-ngsi:
          uri: "https://projectww4zero.pt/dataModel/assemblyBy"
          uri-prefix: "https://projectww4zero.pt/dataModel/"
          type: Relationship


      expedition:
        anyOf:
          - description: 'Relationship property: Identifies project name that is already going from the factory to the owner address'
            maxLength: 256
            minLength: 1
            pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
            type: string
          - description: 'Relationship property: indicates that all the process of some order is going for some address'
            format: uri
            type: string
        description: 'Identification the addres that will recieve the oreder name'
        x-ngsi:
          uri: "https://projectww4zero.pt/dataModel/expedition"
          uri-prefix: "https://projectww4zero.pt/dataModel/"
          type: Relationship


    required:
    - id
    - name