 project:
      title: Project
      type: object
      description: Contains the information of a project
      properties:
        id:
          description: Projects id Identifier
          type: string
          format: uri
          example: urn:ngsi-ld:Project:[uuid]
          x-ngsi:
            type: Property
            
        givename: 
          description: Project name
          type: string
          example: MUEBLE-WC
          x-ngsi:
            uri: "https://schema.org/givename"
            uri-prefix: "https://schema.org/"
            model: https://schema.org/name
            type: Property

        category: #movel wc, movel cozinha, movel 
          description: Movel type
          type: string
          example: Movel cozinha
          x-ngsi:
            uri: "https://projectww4zero.pt/dataModel/category"
            uri-prefix: "https://projectww4zero.pt/dataModel/"
            type: Property



        required:
        - id
        - givename